RoyalGames/
├── app.py              (The Brain: Auth, Slots, Admin, Telegram)
├── requirements.txt    (The Dependencies)
├── templates/          (The Visuals)
│   ├── index.html      (Lobby/Slots)
│   ├── admin.html      (Control Panel)
│   ├── register.html   (Sign Up + Terms)
│   ├── login.html      (Sign In)
│   ├── about.html      (Trust/Info)
│   ├── forgot.html     (OTP Request)
│   ├── verify.html     (OTP Entry)
│   ├── deposit.html    (Telebirr Form)
│   ├── history.html    (User Logs)
│   └── leaderboard.html (Top Players)
